language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-front-end-basic' ]; then cd .. && eval "mv $currentfolder generator-front-end-basic" && cd generator-front-end-basic; fi

